name: discrete_slider
description: Step sliders with custom labels, colors and smooth animations â€” ideal for ratings & progress.
version: 1.0.5

homepage: https://github.com/oddbuddy/flutter_discrete_slider
repository: https://github.com/oddbuddy/flutter_discrete_slider
issue_tracker: https://github.com/oddbuddy/flutter_discrete_slider/issues
documentation: https://pub.dev/documentation/discrete_slider/latest/
topics:
  - slider
  - discrete
  - labeled
  - step
  - customizable

screenshots:
  - description: 'Basic discrete slider with labels'
    path: assets/settings.png
  - description: 'Customized sliders with different styles'
    path: assets/all.png

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: